global:
  volume_dir : "/media/bioinformatics/imidomics_platform_storage/volume/"
  output_dir: "output/"
  tmp_dir: "/media/bioinformatics/imidomics_platform_storage/volume_migration/tmp/"

database:
  host: "10.7.50.21"
  port: 5432  
  name: "platform_db"
  user: "platform_admin"

database_api:
  host: "10.7.50.21"
  port: 8000

database_wrapper:
  R_dir: "../bioinformatics_registry/db_R_wrapper"
  Python_dir: "../bioinformatics_registry/db_Python_wrapper"
  
  