---
title: "02_harmonization"
author: "Sergio"
date: "30/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(TwoSampleMR)
library(MendelianRandomization)
library(data.table)
library(stringr)
library(rtracklayer)
library(liftOver)
library(gwasvcf)

source("../../../../Shared/imidomics/R/readme_generator.R")
source("../../../../Shared/imidomics/R/config.R")
imidomics_config <- readIMIDomicsConfig()
root_data_dir <- imidomics_config$root_data_dir
raw_data_dir <- imidomics_config$raw_data_dir
proj_dir0 <- "/Projects/Internal_Projects/2021_IMX_TargetIdentification_vMR2/"
proj_dir <- "/Projects/Internal_Projects/2021_IMX_TargetIdentification_vMR2/01_MR_eQTL/"
gwas_dir <- "/Projects/Internal_Projects/2021_ExternalDatasets_Mining/SNPs/01_Features/01_Clinical_Association/01_caseCtrl/"
vcf_dir <- paste0(root_data_dir, proj_dir0, "/tmp_files/")
dbfile <- paste0(vcf_dir, "dbfile")
dbfile <- paste0(vcf_dir, "mydb.sqlite")
tic <- Sys.time()
```

# Settings

```{r}
# Plink settings
if(root_data_dir == "/mnt/proteome/bioinformatics"){
  Sys.setenv(PATH=paste("/mnt/nfs_home/smartinez/tools/bcftools/", Sys.getenv("PATH"), sep=":"))
  plink_bin <- "/mnt/nfs_home/smartinez/tools/plink/plink"
  set_plink(plink_bin)
  set_bcftools(path = "/mnt/nfs_home/smartinez/tools/bcftools/bcftools")
  plink_ref <- "/mnt/proteome/bioinformatics/Data/Molecular/Biological_Annotations/1000G/EUR"
  # eur.bim <- fread("/dev/shm/tmp_files/EUR.bim")
  # eur.bim <- fread("/mnt/proteome/bioinformatics/Data/Molecular/Biological_Annotations/1000G/EUR.bim")
} else{
  Sys.setenv(PATH=paste("/home/sergio/", Sys.getenv("PATH"), sep=":"))
  plink_bin <- "/home/sergio/bin/plink"
  plink_ref <- "/media/bioinformatics/Data/Molecular/Biological_Annotations/1000G/EUR"
  # eur.bim <- fread("/media/bioinformatics/Data/Molecular/Biological_Annotations/1000G/EUR.bim")
  set_plink(path = plink_bin)
  set_bcftools(path = "/home/sergio/bcftools/bcftools")
}

# Choose studies
studies <- c("ieu-a-833", "finn-b-L12_PSORI_ARTHRO", "ebi-a-GCST004132", "ebi-a-GCST004133", "ebi-a-GCST003156", "ebi-a-GCST90019017")
names(studies) <- c("RA_Okada2014", "PSA_Finn2021", "CD_deLange2017", "UC_deLange2017", "SLE_Bentham2015", "PS_Stuart2022")
```

# Extract outcomes

# Harmonize

```{r}
for(i in 1:3){
  
  # Provisional instruments
  ins <- readRDS(paste0(root_data_dir, proj_dir, "/01_eQTL_Instruments/IS", i, ".rds"))
  
  for(name in names(studies)){
    vcf <- query_gwas(vcf = paste0(root_data_dir, gwas_dir, "/", name, "/", studies[name], ".vcf.gz"), rsid = ins$SNP, proxies = "yes", dbfile = dbfile, tag_r2 = 0.8)
    out.dat <- gwasglue::gwasvcf_to_TwoSampleMR(vcf, "outcome")
    # out.dat <- out.dat[out.dat$beta.outcome!=0,]
    
    # Harmonize
    har <- harmonise_data(exposure_dat = ins, outcome_dat = out.dat)
    
    # Filter palindromic SNPs with intermediate freqs
    # har <- har[which(har$palindromic==F | har$ambiguous==F),]
    
    # Save
    saveRDS(har, file = paste0(root_data_dir, proj_dir, "/02_Harmonized/", name, "_IS", i, ".rds"))
  }
}
```


```{r}
toc <- Sys.time()
temps <- as.numeric(difftime(toc, tic, units='mins'))
readme(path = paste0(root_data_dir, proj_dir, "/README"),
       subanalisi = 3,
       titol = "Harmonization",
       autors = "Sergio",
       lloc = "03_harmonization.Rmd",
       temps = temps,
       descripcio = "",
       altres = "")
```

# Check differences with previous

```{r}
studies <- c("RA_Okada2014", "PS_Stuart2022", "CD_deLange2017", "UC_deLange2017", "SLE_Bentham2015", "PSA_Finn2021")

# Available outcomes from TwoSampleMR
ao <- readRDS(paste0(root_data_dir, "/Projects/Internal_Projects/2021_IMX_TargetIdentification_vMR2/tmp_files/opengwas_availableoutcomes.rds"))
ids <- ao$id[ao$author=="Vosa U"]
genes <- gsub(".*-", "", ids)
ensembl.tss <- readRDS(paste0(root_data_dir, proj_dir, "/Annotations/All_ENS_SYMB_TSS_v37.rds"))
genes <- genes[genes %in% ensembl.tss$ensembl_gene_id]

# Function to compute sorted set of SNPs per gene
sig_per_gene <- function(df) {
  # keep unique (gene, SNP) pairs
  u <- unique(df[c("exposure", "SNP")])
  # ensure character for consistent pasting
  u$SNP <- as.character(u$SNP)
  # split SNPs by gene, sort within gene, paste into a single string
  sp <- split(u$SNP, u$exposure, drop = TRUE)
  sig <- vapply(sp, function(v) paste(sort(v), collapse = ","), character(1L))
  data.frame(gene = names(sig), sig = unname(sig), stringsAsFactors = FALSE, row.names = NULL)
}

res_list <- vector("list", length(studies) * 3L)
k <- 1L
for(s in studies){
  for(j in 1:3){
    har1 <- readRDS(paste0(root_data_dir, proj_dir, "/02_Harmonized/", s, "_IS", j, ".rds"))
    har1 <- har1[which(har1$palindromic==F | har1$ambiguous==F),]
    har2 <- readRDS(paste0(root_data_dir, proj_dir, "/02_Harmonized/220603/", s, "_IS", j, ".rds"))
    har2 <- har2[which(har2$palindromic==F | har2$ambiguous==F),]
    if(s == "PS_Stuart2022") har2$SNP <- har2$rsid
  
    sig1 <- sig_per_gene(har1)
    sig2 <- sig_per_gene(har2)
    
    res <- merge(sig1, sig2, by = "gene", all = TRUE, suffixes = c("1", "2"))
    res$gene <- gsub(".*-", "", res$gene)
    
    TODO <- res$sig1 != res$sig2 | (is.na(res$sig2) & !is.na(res$sig1))
    TOREMOVE <- is.na(res$sig1) & !is.na(res$sig2)
    
    res_list[[k]] <- data.frame(
      Var1 = s, Var2 = j, Var3 = res$gene,
      TODO = TODO, TOREMOVE = TOREMOVE,
      stringsAsFactors = FALSE
    )
    k <- k + 1L
  }
}
RES <- do.call(rbind, res_list)

table(RES$Var1, RES$Var2, RES$TODO)
table(RES$Var1, RES$Var2, RES$TOREMOVE)
saveRDS(RES, file = paste0(root_data_dir, proj_dir, "/02_Harmonized/checkToUpdate.rds"))
```

# Remove?

```{r}
# To remove estimation results from copied folder
for(s in studies){
  for(j in 1:3){
    for(p in RES$Var3[which(RES$Var1==s & RES$Var2==j & RES$TOREMOVE==T)]){
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_Main.rds"))
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_Heterogeneity.rds"))
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_SNPs.rds"))
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_Pleiotropy.rds"))
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_LOO.rds"))
      system(paste0("rm ", root_data_dir, proj_dir, "/03_EstimationResults/perGene/", p, "_", s, "_IS", j, "_Steiger.rds"))
    }
  }
}
```
